<?php

/**
 * @file
 * Contains core functionality for the Lightning distribution.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityDescriptionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\lightning_core\ConfigHelper as Config;
use Drupal\lightning_core\Element as ElementHelper;
use Drupal\lightning_core\Entity\EntityFormMode;
use Drupal\lightning_core\Entity\EntityViewMode;
use Drupal\lightning_core\Entity\Role;
use Drupal\lightning_core\Form\EntityDisplayModeAddForm;
use Drupal\lightning_core\Form\EntityDisplayModeEditForm;
use Drupal\lightning_core\Form\EntityFormModeAddForm;
use Drupal\lightning_core\Form\RoleForm;
use Drupal\lightning_core\OverrideHelper as Override;
use Drupal\path\Plugin\Field\FieldType\PathFieldItemList;

/**
 * Conditionally overrides the class specified by a plugin definition.
 *
 * The class is overridden only if the replacement class' immediate parent is
 * the one in the plugin definition.
 *
 * @param array $definition
 *   The plugin definition.
 * @param string $replacement_class
 *   The replacement class.
 *
 * @return string
 *   The chosen plugin class.
 *
 * @deprecated in Lightning 2.0.5 and will be removed in Lightning 2.1.0. Use
 * OverrideHelper::pluginClass() instead.
 */
function lightning_core_override_plugin_class(array &$definition, $replacement_class) {
  Override::pluginClass($definition, $replacement_class);
  return $definition['class'];
}

/**
 * Implements hook_entity_type_alter().
 */
function lightning_core_entity_type_alter(array &$entity_types) {
  Override::entityClass($entity_types['user_role'], Role::class);
  Override::entityClass($entity_types['entity_view_mode'], EntityViewMode::class);
  Override::entityClass($entity_types['entity_form_mode'], EntityFormMode::class);

  Override::entityForm($entity_types['user_role'], RoleForm::class);

  Override::entityForm($entity_types['entity_view_mode'], EntityDisplayModeAddForm::class, 'add');
  Override::entityForm($entity_types['entity_view_mode'], EntityDisplayModeEditForm::class, 'edit');

  Override::entityForm($entity_types['entity_form_mode'], EntityFormModeAddForm::class, 'add');
  Override::entityForm($entity_types['entity_form_mode'], EntityDisplayModeEditForm::class, 'edit');
}

/**
 * Implements hook_element_info_alter().
 */
function lightning_core_element_info_alter(array &$info) {
  // Add support for the #legend property to checkboxes and radios.
  // @see Element::processLegend()
  $info['radios']['#legend'] = $info['checkboxes']['#legend'] = [];
  $info['radios']['#process'][] = $info['checkboxes']['#process'][] = [ElementHelper::class, 'processLegend'];
}

/**
 * Implements hook_help().
 */
function lightning_core_help($route_name, RouteMatchInterface $route_match) {
  $matched = [];
  // Parse the route name to figure out what display mode we're looking at:
  // 0 is the entire string.
  // 1 is 'view' or 'form'.
  // 2 is the ID of the affected entity type.
  // 3 is 'view_mode' or 'form_mode'.
  // 4 is 'view' or 'form'.
  $expr = '/^entity\.entity_(view|form)_display\.([a-z_]+)\.((view|form)_mode)$/';

  if (preg_match($expr, $route_name, $matched)) {
    $entity_id = sprintf(
      '%s.%s',
      $route_match->getParameter('entity_type_id'),
      $route_match->getParameter($matched[3] . '_name')
    );

    $display_mode = \Drupal::entityTypeManager()
      ->getStorage('entity_' . $matched[3])
      ->load($entity_id);

    if ($display_mode instanceof EntityDescriptionInterface) {
      $description = $display_mode->getDescription();
      if ($description) {
        return '<p>' . $description . '</p>';
      }
    }
  }
}

/**
 * Implements hook_modules_installed().
 */
function lightning_core_modules_installed(array $modules) {
  if (in_array('token', $modules)) {
    $view_modes = [];
    foreach (\Drupal::entityTypeManager()->getDefinitions() as $entity_type) {
      $view_modes[] = $entity_type->id() . '.token';
    }

    $view_modes = EntityViewMode::loadMultiple($view_modes);
    /** @var \Drupal\Core\Entity\EntityViewModeInterface $view_mode */
    foreach ($view_modes as $view_mode) {
      $view_mode->setThirdPartySetting('lightning_core', 'internal', TRUE)
        ->save();
    }
  }
}

/**
 * Implements hook_entity_load().
 */
function lightning_core_entity_load(array $entities) {
  // Maintain a list of entity UUIDs whose aliases we've already looked up.
  // We only want to look up a particular entity's alias once per request in
  // order to prevent infinite loops (see issue #2831550).
  static $looked_up = [];

  /** @var \Drupal\Core\Path\AliasStorageInterface $alias_storage */
  $alias_storage = \Drupal::service('path.alias_storage');

  foreach ($entities as $entity) {
    $uuid = $entity->uuid();

    // If the entity has an empty path field, try to set its value. Amazingly,
    // Path does not do this on its freaking own.
    if (
      empty($looked_up[$uuid]) &&
      $entity instanceof FieldableEntityInterface &&
      $entity->hasField('path') &&
      $entity->path instanceof PathFieldItemList &&
      $entity->path->isEmpty()
    ) {
      $looked_up[$uuid] = TRUE;

      $alias = $alias_storage->load([
        'source' => '/' . $entity->toUrl()->getInternalPath(),
      ]);

      if ($alias) {
        $entity->path->setValue($alias);
      }
    }
  }
}

/**
 * Puts an associative array into an arbitrary order.
 *
 * @param array $values
 *   The array to reorder.
 * @param array $keys
 *   The keys, in their desired order.
 *
 * @deprecated in Lightning 2.0.3 and will be removed in Lightning 2.1.0. Use
 * \Drupal\lightning_core\Element::order() instead.
 */
function array_reorder(array &$values, array $keys) {
  ElementHelper::order($values, $keys);
}

/**
 * Pre-render function to disable all buttons in a renderable element.
 *
 * @param array $element
 *   The renderable element.
 *
 * @return array
 *   The renderable element with all buttons (at all levels) disabled.
 *
 * @deprecated in Lightning 2.0.3 and will be removed in Lightning 2.1.0. Use
 * \Drupal\lightning_core\Element::disableButtons() instead.
 */
function lightning_core_disable_buttons(array $element) {
  return ElementHelper::disableButtons($element);
}

/**
 * Implements hook_block_view_alter().
 */
function lightning_core_block_view_alter(array &$build, BlockPluginInterface $block) {
  \Drupal::service('renderer')->addCacheableDependency($build, $block);

  // Always add block_view:BASE_PLUGIN_ID as a cache tag.
  $build['#cache']['tags'][] = 'block_view:' . $block->getBaseId();

  // If the plugin is a derivative, add block_view:FULL_PLUGIN_ID as well.
  if ($block->getDerivativeId()) {
    $build['#cache']['tags'][] = 'block_view:' . $block->getPluginId();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lightning_core_form_user_form_alter(array &$form) {
  if (isset($form['account']['roles'])) {
    /** @var \Drupal\user\RoleInterface $role */
    foreach (Role::loadMultiple() as $id => $role) {
      if ($role instanceof EntityDescriptionInterface) {
        $form['account']['roles']['#legend'][$id] = $role->getDescription();
      }
    }
  }
}

/**
 * Rebuilds the service container.
 */
function lightning_core_rebuild_container() {
  require_once \Drupal::root() . '/core/includes/utility.inc';
  $class_loader = \Drupal::service('class_loader');
  $request = \Drupal::request();
  drupal_rebuild($class_loader, $request);
}

/**
 * Implements template_preprocess_block().
 */
function lightning_core_preprocess_block(array &$variables) {
  $variables['attributes']['data-block-plugin-id'] = $variables['elements']['#plugin_id'];
}

/**
 * Creates a config entity from default configuration.
 *
 * @param string $entity_type
 *   The config entity type ID.
 * @param string $id
 *   The unprefixed entity ID.
 * @param string $module
 *   (optional) The module which has the default configuration.
 *
 * @deprecated in Lightning 2.0.3 and will be removed in Lightning 2.1.0. Use
 * the ConfigHelper facade instead.
 */
function lightning_core_create_config($entity_type, $id, $module = 'lightning_core') {
  Config::forModule($module)->getEntity($entity_type, $id)->save();
}

/**
 * Reads a stored config file from a module's config/install directory.
 *
 * @param string $id
 *   The config ID.
 * @param string $module
 *   (optional) The module to search. Defaults to 'lightning_core'.
 *
 * @return array
 *   The config data.
 *
 * @deprecated in Lightning 2.0.3 and will be removed in Lightning 2.1.0. Use
 * the ConfigHelper facade instead.
 */
function lightning_core_read_config($id, $module = 'lightning_core') {
  return Config::forModule($module)->read($id);
}
