<?php

/**
 * @file
 * Contains core functionality for the Lightning distribution.
 */

use Drupal\node\NodeTypeInterface;
use Drupal\user\Entity\Role;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function lightning_core_node_type_insert(NodeTypeInterface $node_type) {
  Role::create([
    'id' => $node_type->id() . '_creator',
    'label' => t('@type Creator', [
      '@type' => $node_type->label(),
    ]),
    'permissions' => [
      'create ' . $node_type->id() . ' content',
      'edit own ' . $node_type->id() . ' content',
      'view ' . $node_type->id() . ' revisions',
      'view own unpublished content',
      'create url aliases',
    ],
  ])->save();

  Role::create([
    'id' => $node_type->id() . '_reviewer',
    'label' => t('@type Reviewer', [
      '@type' => $node_type->label(),
    ]),
    'permissions' => [
      'edit any ' . $node_type->id() . ' content',
      'delete any ' . $node_type->id() . ' content',
    ],
  ])->save();
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function lightning_core_node_type_delete(NodeTypeInterface $node_type) {
  $role = Role::load($node_type->id() . '_creator');
  if ($role) {
    $role->delete();
  }

  $role = Role::load($node_type->id() . '_reviewer');
  if ($role) {
    $role->delete();
  }
}
