<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function lightning_inline_block_entity_delete(EntityInterface $entity) {
  $entity_id = $entity->id();

  if (is_numeric($entity_id)) {
    \Drupal::database()
      ->delete('inline_entity')
      ->condition('entity_type', $entity->getEntityTypeId())
      ->condition('entity_id', $entity_id)
      ->execute();
  }
}

/**
 * Implements hook_panels_ipe_blocks_alter().
 */
function lightning_inline_block_panels_ipe_blocks_alter(array &$blocks = []) {
  foreach ($blocks as $i => $block) {
    if ($block['provider'] == 'lightning_inline_block') {
      unset($blocks[$i]);
    }
  }
}
