<?php

/**
 * @file
 * Support for document media assets in Lightning.
 */

use Drupal\lightning_core\OverrideHelper as Override;
use Drupal\lightning_media_document\Plugin\MediaEntity\Type\Document;

/**
 * Implements hook_media_entity_type_info_alter().
 */
function lightning_media_document_media_entity_type_info_alter(array &$types) {
  $types['document']['input_match']['field_types'] = ['file'];
  Override::pluginClass($types['document'], Document::class);
}
