# This file is used by Acquia Pipelines continuous integration. It builds
# Lightning and runs its functional tests. Upon success, an artifact is deployed
# to the lightningnightly (92170259-5e36-4052-a2ad-0dd5ee5b3ec2) sub on Acquia
# cloud.
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.2

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/vendor/bin:$PATH"
            - composer validate --no-check-all --ansi --no-interaction
            - composer update
      - cleanup:
          type: script
          script:
            # Setup settings file and codebase with minimum required for cloud.
            - chmod -R +w docroot/sites/default
            - cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php
            - echo "if (file_exists('/var/www/site-php')) { require '/var/www/site-php/lightningnightly/lightningnightly-settings.inc';}" >> docroot/sites/default/settings.php
            # Clear any config directories that Cloud tries to set in th include
            # file.
            - echo "\$config_directories = [];" >> docroot/sites/default/settings.php
            # Use the existing `config` directory we already have. Cloud get's
            # confused because we have a config directory above docroot already
            # and manipulating it in Pipelines doesn't seem to work. This
            # deployment is ephemeral, so using the existing config directory
            # isn't a problem.
            - echo "\$config_directories['sync'] = '../config';" >> docroot/sites/default/settings.php
