# This file is used by Acquia Pipelines continuous integration. It builds
# Lightning and runs its functional tests. Upon success, an artifact is deployed
# to the lightningnightly (92170259-5e36-4052-a2ad-0dd5ee5b3ec2) sub on Acquia
# cloud.
version: 1.0.0
services:
  - mysql

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install
      - install:
          type: script
          script:
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - ./bin/phing install -Ddb.password=root -Ddb.database=drupal -Durl=http://127.0.0.1:8080
            # Reset the settings file and add cloud DB snippet.
            - ./bin/phing reset-settings
            - mkdir -p ./config/default
      - test:
          type: script
          script:
            - cd docroot
            - ../bin/drush runserver --default-server=builtin 8080 &>/dev/null &
            - ../bin/phantomjs --webdriver=4444 > /dev/null &
            - sleep 10
            - ../bin/behat --stop-on-failure --config ./sites/default/files/behat.yml --tags=~javascript
