# This file is used by Acquia Pipelines continuous integration. It builds
# Lightning and runs its functional tests. Upon success, an artifact is deployed
# to the lightningnightly (92170259-5e36-4052-a2ad-0dd5ee5b3ec2) sub on Acquia
# cloud.
version: 1.0.0
services:
  - mysql

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - mkdir -p ./config/sync
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$BUILD_DIR/bin:$PATH"
            - composer validate --no-check-all --ansi
            - composer install
      - install:
          type: script
          script:
            - cd $BUILD_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - phing install -Ddb.password=root -Ddb.database=drupal -Durl=http://127.0.0.1:8080
      - test:
          type: script
          script:
            - cd $BUILD_DIR/docroot
            - drush runserver --default-server=builtin 8080 &>/dev/null &
            - phantomjs --webdriver=4444 > /dev/null &
            - sleep 10
            - behat --stop-on-failure --config ./sites/default/files/behat.yml --tags=~javascript
      - cleanup:
          type: script
          script:
            # Reset the settings file and add cloud DB snippet.
            - cd $BUILD_DIR
            - phing reset-settings
