# This file is used by Acquia Pipelines continuous integration. It builds
# Lightning and runs its functional tests. Upon success, an artifact is deployed
# to the lightningnightly (92170259-5e36-4052-a2ad-0dd5ee5b3ec2) sub on Acquia
# cloud.
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.1

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/vendor/bin:$PATH"
            - composer validate --no-check-all --ansi --no-interaction
            - composer update
      - install:
          type: script
          script:
            - cd $SOURCE_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - lightning install 'mysql\://root:root@localhost/drupal' lightning 'http://127.0.0.1:8080'
      - test:
          type: script
          script:
            - cd $SOURCE_DIR/docroot
            - drush runserver --default-server=builtin 8080 &>/dev/null &
            - phantomjs --webdriver=4444 > /dev/null &
            - sleep 10
            - cd $SOURCE_DIR
            - behat --stop-on-failure --config .behat.yml --tags=~javascript
      - cleanup:
          type: script
          script:
            - cd $SOURCE_DIR
            # Setup settings file and codebase with minimum required for cloud.
            - lightning configure:cloud
            # Remove the Drush binary and package so it doesn't interfere with
            # cloud versions. Doing this the proper way with Composer can cause
            # timeouts.
            - rm ./vendor/bin/drush
            - rm -rf ./vendor/drush
