#!/usr/bin/env php
<?php

require_once './vendor/autoload.php';

$encoder = new \Acquia\Lightning\IniEncoder();

$make = \Symfony\Component\Yaml\Yaml::parse(`./bin/drush make-convert composer.lock`);

// drush make-convert considers non-Drupal Composer dependencies, like Drush,
// to be libraries. That is totally wrong, so head that off at the pass by
// destroying any libraries it thinks it's found.
unset($make['libraries']);

if (isset($make['projects']['drupal'])) {
  // Always use drupal.org's core repository, or patches will not apply.
  $make['projects']['drupal']['download']['url'] = 'https://git.drupal.org/project/drupal.git';

  $core = [
    'api' => 2,
    'core' => '8.x',
    'projects' => [
      'drupal' => [
        'type' => 'core',
        'version' => $make['projects']['drupal']['download']['tag'],
      ],
    ],
  ];
  if (isset($make['projects']['drupal']['patch'])) {
    $core['projects']['drupal']['patch'] = $make['projects']['drupal']['patch'];
  }
  file_put_contents('drupal-org-core.make', $encoder->encode($core));
  unset($make['projects']['drupal']);
}

foreach ($make['projects'] as $key => &$project) {
  if ($project['download']['type'] == 'git') {
    $tag = $project['download']['tag'];
    preg_match('/[0-9]\.x-[0-9]\.0/', $tag, $match);
    $tag = str_replace($match, str_replace('x-', NULL, $match), $tag);
    preg_match('/[0-9]\.[0-9]\.0/', $tag, $match);
    $tag = str_replace($match, substr($match[0], 0, -2), $tag);
    $project['version'] = $tag;
    unset($project['download']);
  }
}

file_put_contents('drupal-org.make', $encoder->encode($make));
