<?php
/**
 * @file
 * Code for the Lightning Demo feature.
 */

include_once 'lightning_demo.features.inc';

/**
 * Implements hook_migrate_api().
 */
function lightning_demo_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'LightningDemoFilesImage' => array('class_name' => 'LightningDemoFilesImage', 'group_name' => 'lightning_demo'),
      'LightningDemoNodesArticle' => array('class_name' => 'LightningDemoNodesArticle', 'group_name' => 'lightning_demo'),
      'LightningDemoUsers' => array('class_name' => 'LightningDemoUsers', 'group_name' => 'lightning_demo'),
      'LightningDemoHTMLFPP' => array('class_name' => 'LightningDemoHTMLFPP', 'group_name' => 'lightning_demo'),
    ),
  );
  return $api;
}

