<?php

/**
 * @file
 * Layout enhancements for the Lightning distribution.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lightning_layout_form_entity_view_display_form_alter(array &$form, FormStateInterface $form_state) {
  // We need to alter elements added by Panelizer's implementation of this hook.
  $form['#process'][] = 'lightning_layout_panelizer_opt_in';
}

/**
 * Process callback for entity_view_display_form.
 *
 * @param array $form
 *   The completed form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return array
 *   The processed form.
 */
function lightning_layout_panelizer_opt_in(array $form, FormStateInterface $form_state) {
  if (isset($form['panelizer'])) {
    $panelizer_settings = $form_state->getFormObject()
      ->getEntity()
      ->getThirdPartySettings('panelizer');

    // If there are no Panelizer settings at all, opt in by default.
    if (empty($panelizer_settings)) {
      $form['panelizer']['enable']['#default_value'] = TRUE;
      $form['panelizer']['custom']['#default_value'] = TRUE;
    }
  }
  return $form;
}
