core.entity_view_mode.*.*.third_party.lightning_core:
  type: mapping
  label: 'Lightning'
  mapping:
    description:
      type: string
      label: 'Description'
    internal:
      type: boolean
      label: 'Internal'
