lightning_core.content_role:
  type: mapping
  label: 'Content role'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    label:
      type: string
      label: 'Label'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        type: string
        label: 'Permission'

lightning_core.settings:
  type: config_object
  label: 'Lightning settings'
  mapping:
    content_roles:
      type: sequence
      label: 'Content roles'
      sequence:
        type: lightning_core.content_role
        label: 'Content role'
    entity_block:
      type: mapping
      label: 'Entity Block plugin settings'
      mapping:
        blacklist:
          type: sequence
          label: 'Entity type blacklist'
          sequence:
            type: string
            label: 'Entity type ID'
