<?php

/**
 * @file
 * Contains landing page functionality for Lightning.
 */

use Drupal\field\FieldConfigInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function lightning_landing_page_field_config_insert(FieldConfigInterface $field) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  elseif ($field->id() == 'node.landing_page.field_meta_tags') {
    $component = [
      'type' => 'metatag_empty_formatter',
      'region' => 'content',
    ];

    entity_get_display('node', 'landing_page', 'default')
      ->setComponent('field_meta_tags', $component)
      ->save();

    entity_get_display('node', 'landing_page', 'full')
      ->setComponent('field_meta_tags', $component)
      ->save();

    entity_get_display('node', 'landing_page', 'teaser')
      ->setComponent('field_meta_tags', $component)
      ->save();

    entity_get_form_display('node', 'landing_page', 'default')
      ->setComponent('field_meta_tags', [
        'type' => 'metatag_firehose',
        'region' => 'content',
      ])
      ->save();
  }
}

/**
 * Implements hook_modules_installed().
 */
function lightning_landing_page_modules_installed(array $modules) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  elseif (in_array('lightning_search', $modules)) {
    $node_type = NodeType::load('landing_page');
    lightning_search_node_type_insert($node_type);
  }
}
