<?php

/**
 * @file
 * Support for instagram posts as media entities in Lightning.
 */

use Drupal\lightning_core\OverrideHelper as Override;
use Drupal\lightning_media_instagram\Plugin\media\Source\Instagram;

/**
 * Implements hook_media_source_info_alter().
 */
function lightning_media_instagram_media_source_info_alter(array &$sources) {
  $sources['instagram']['input_match'] = [
    'constraint' => 'InstagramEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $sources['instagram']['preview'] = TRUE;

  Override::pluginClass($sources['instagram'], Instagram::class);
}
