<?php

/**
 * @file
 * Contains Search API integration for Lightning.
 */

/**
 * Implements hook_entity_type_alter().
 */
function lightning_search_entity_type_alter(array &$entity_types) {
  // Search API tasks are internal content entities and should never be
  // workspace-aware or otherwise under Multiversion control (unless they have
  // already been taken over, which case you're on your own).
  if (isset($entity_types['search_api_task']) && !\Drupal::state()->get('multiversion.migration_done.search_api_task')) {
    $entity_types['search_api_task']->set('multiversion', FALSE);
  }
}
