node.type.*.third_party.lightning_scheduled_updates:
  type: mapping
  label: 'Lightning Scheduled Updates settings'
  mapping:
    embargo:
      type: boolean
      label: 'Enable embargo for this node type'
