bg_image_formatter: 1.6.0
blazy: 1.0.0-rc4
block: 8.6.9
block_content: 8.6.9
breakpoint: 8.6.9
ckeditor: 8.6.9
config: 8.6.9
consumers: 1.5.0
contact: 8.6.9
contact_storage: 1.0.0-beta9
content_moderation: 8.6.9
contextual: 8.6.9
crop: 2.0.0-rc1
ctools: 3.1.0
datetime: 8.6.9
dblog: 8.6.9
diff: 1.0.0-rc2
dropzonejs: 2.0.0-alpha3
editor: 8.6.9
embed: 1.0.0
entity_block: 1.0.0-beta1
entity_browser: 2.0.0
entity_embed: 1.0.0-beta2
entity_reference: 8.6.9
field: 8.6.9
field_ui: 8.6.9
file: 8.6.9
filter: 8.6.9
help: 8.6.9
history: 8.6.9
image: 8.6.9
image_widget_crop: 2.2.0
inline_entity_form: 1.0.0-rc1
jsonapi: 2.1.0
layout_builder: 8.6.9
layout_builder_restrictions: 1.4.0
layout_discovery: 8.6.9
layout_library: 1.0.0-alpha1
libraries: 3.0.0-alpha1
lightning_core: 3.6.0
lightning_install: 4.000.0-alpha6
link: 8.6.9
media: 8.6.9
media_library: 8.6.9
menu_ui: 8.6.9
node: 8.6.9
options: 8.6.9
page_cache: 8.6.9
path: 8.6.9
quickedit: 8.6.9
rdf: 8.6.9
search_api: 1.11.0
serialization: 8.6.9
shortcut: 8.6.9
system: 8.6.9
taxonomy: 8.6.9
text: 8.6.9
token: 1.5.0
toolbar: 8.6.9
user: 8.6.9
views_ui: 8.6.9
workflows: 8.6.9
menu_link_content: 8.6.9
views: 8.6.9
schemata: 1.0.0-alpha5
schemata_json_schema: 1.0.0-alpha5
openapi: 1.0.0-beta2
openapi_ui: 1.0.0-rc1
openapi_ui_redoc: 1.0.0-rc2
openapi_ui_swagger: 1.0.0-rc3
simple_oauth: 3.14.0
simple_oauth_extras: 3.14.0
lightning_api: 3.3.0
lightning_contact_form: 3.6.0
lightning_page: 3.6.0
lightning_roles: 3.6.0
search_api_db: 1.11.0
lightning_search: 3.6.0
lightning_layout: 2.0.0-alpha10
lightning_banner_block: 2.0.0-alpha10
lightning_landing_page: 2.0.0-alpha10
simple_gmap: 1.4.0
lightning_map_block: 2.0.0-alpha10
views_infinite_scroll: 1.5.0
lightning_media: 3.6.0
entity_browser_block: 1.0.0-alpha1
lightning_media_audio: 3.6.0
lightning_media_bulk_upload: 3.6.0
lightning_media_document: 3.6.0
lightning_media_image: 3.6.0
media_entity_instagram: 2.0.0-alpha2
lightning_media_instagram: 3.6.0
slick: 1.1.0
slick_entityreference: 1.1.0
lightning_media_slideshow: 3.6.0
media_entity_twitter: 2.0.0-alpha2
lightning_media_twitter: 3.6.0
video_embed_field: 2.0.0
video_embed_media: 2.0.0
lightning_media_video: 3.6.0
lightning_workflow: 3.3.0
lightning_scheduler: 3.3.0
metatag: 1.7.0
page_manager: 4.0.0-beta3
panels: 4.3.0
moderation_dashboard: 1.0.0-beta1
moderation_sidebar: 1.1.0
pathauto: 1.3.0
lightning: 4.000.0-alpha6
update: 8.6.9
devel_generate: 1.2.0
lightning_dev: 2.x-dev
