<?php

/**
 * @file
 * Contains installation routines for Lightning Test.
 */

use Drupal\entity_browser\Element\EntityBrowserElement;

/**
 * Implements hook_install().
 */
function lightning_test_install() {
  entity_get_form_display('node', 'page', 'default')
    ->setComponent('field_multi_image', [
      'type' => 'entity_browser_file',
      'settings' => [
        'entity_browser' => 'image_browser',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'view_mode' => 'default',
        'preview_image_style' => 'thumbnail',
        'open' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
      ],
    ])
    ->setComponent('field_hero_image', [
      'type' => 'entity_browser_file',
      'settings' => [
        'entity_browser' => 'image_browser',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'view_mode' => 'default',
        'preview_image_style' => 'thumbnail',
        'open' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
      ],
    ])
    ->setComponent('field_unlimited_images', [
      'type' => 'entity_browser_file',
      'settings' => [
        'entity_browser' => 'image_browser',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'view_mode' => 'default',
        'preview_image_style' => 'thumbnail',
        'open' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
      ],
    ])
    ->setComponent('field_media_reference', [
      'type' => 'entity_browser_entity_reference',
      'settings' => [
        'entity_browser' => 'media_browser',
        'field_widget_display' => 'rendered_entity',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
        'field_widget_display_settings' => [
          'view_mode' => 'embedded',
        ],
        'open' => TRUE,
      ],
    ])
    ->save();
}

/**
 * Implements hook_uninstall().
 */
function lightning_test_uninstall() {
  \Drupal::service('lightning.config_helper')
    ->install('lightning_test')
    ->deleteAll();

  // Delete any content created while this module was enabled.
  $expendables = \Drupal::state()->get('lightning_test', []);

  foreach ($expendables as $entity_type => $ids) {
    $storage = \Drupal::entityTypeManager()
      ->getStorage($entity_type);

    $entities = $storage->loadMultiple($ids);

    method_exists($storage, 'purge')
      ? $storage->purge($entities)
      : $storage->delete($entities);
  }

  entity_get_form_display('node', 'page', 'default')
    ->removeComponent('field_multi_image')
    ->removeComponent('field_hero_image')
    ->removeComponent('field_unlimited_images')
    ->save();

  \Drupal::state()->delete('lightning_test');
}
