<?php

/**
 * Implements hook_modules_installed().
 */
function lightning_dev_modules_installed(array $modules) {
  if (in_array('lightning_roles', $modules)) {
    \Drupal::service('lightning.content_roles')
      ->grantPermissions('reviewer', [
        'access content overview',
        'use published_archived transition',
        'view moderation states',
      ]);
  }
  if (in_array('lightning_api', $modules)) {
    \Drupal::configFactory()
      ->getEditable('lightning_api.settings')
      ->set('entity_json', TRUE)
      ->save();
  }
}
