<?php

/**
 * Implements hook_modules_installed().
 */
function lightning_dev_modules_installed(array $modules) {
  array_walk($modules, [
    \Drupal::service('lightning_dev.behat'),
    'add'
  ]);

  if (in_array('lightning_roles', $modules)) {
    \Drupal::service('lightning.content_roles')
      ->grantPermissions('reviewer', [
        'access content overview',
        'use published_archived transition',
        'view moderation states',
      ]);
  }
}
