<?php

use Drupal\node\Entity\NodeType;

/**
 * Implements hook_install().
 */
function lightning_roles_install() {
  // Don't modify configuration if it is currently being synced.
  // @see https://www.drupal.org/node/2870864#comment-12044705
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Create content roles for all existing node types.
  $node_types = NodeType::loadMultiple();
  array_walk($node_types, 'lightning_roles_node_type_insert');
}
