# This is used only by lightning_scheduled_updates, but for some reason the
# config schema checker cannot see config schema defined in sub-components.
# So, we need to do it here instead. Go figure!
node.type.*.third_party.lightning_scheduled_updates:
  type: mapping
  label: 'Lightning Scheduled Updates settings'
  mapping:
    embargo:
      type: boolean
      label: 'Enable embargo for this node type'
